INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES(10001,'Rohan','Learn JPA', SYSDATE(), FALSE)
INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES(10002,'Rohan','Learn 2', SYSDATE(), FALSE)
INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES(10003,'Rohan','Learn 3', SYSDATE(), FALSE)
INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, IS_DONE) VALUES(10004,'Rohan1','Learn 4', SYSDATE(), FALSE)